// Desde acá hago las llamadas al servidor utilizando la extensión REST Client

### Ruta que devuelve todos los productos
GET http://localhost:8080/api/products

### Ruta que devuelve un máximo de 3 productos 
GET http://localhost:8080/api/products?limit=3

### Ruta que devuelve un producto por ID
GET http://localhost:8080/api/products/5

### Ruta para agregar un producto
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "title": "Producto prueba POST",
    "description": "Este es un producto prueba para POST",
    "price": 120,
    "code": "abc128",
    "stock": 23,
    "category": "Pop",
    "status": true
}

### Ruta para actualizar el producto 3
PUT http://localhost:8080/api/products/3
Content-Type: application/json

{
    "title": "Producto actualizado",
    "description": "Este es un producto al cual se le aumentó el precio",
    "price": 170
}

### Ruta para eliminar el producto 6
DELETE http://localhost:8080/api/products/6

### Ruta para crear un carrito
POST http://localhost:8080/api/carts/

### Ruta para mostrar el carrito 1
GET http://localhost:8080/api/carts/1

### Ruta para agregar el producto 3 al carrito 1
POST http://localhost:8080/api/carts/1/product/3

### Ruta para agregar el producto 4 al carrito 1 (aumenta la cantidad)
POST http://localhost:8080/api/carts/1/product/4